packaging_format = 2

id = "glpi"
name = "GLPI"
description.en = "IT Asset Management"
description.fr = "Gestion des services informatiques (ITSM)"

version = "10.0.20~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0"
website = "https://glpi-project.org"
admindoc = "https://glpi-install.readthedocs.io/en/latest/"
code = "https://github.com/glpi-project/glpi"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/glpi"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    ask.pt_BR = "Escolha o idioma do aplicativo"
    type = "select"
    choices = ["ar_IQ", "ar_SA", "ar_SY", "az_AZ", "be_BY", "bg_BG", "bn_BD", "ca_ES", "cs_CZ", "da_DK", "de_DE", "el_GR", "en_GB", "en_US", "eo"   , "es_419", "es_AR", "es_CL", "es_CO", "es_EC", "es_ES", "es_MX", "es_VE", "et_EE", "eu_ES", "fa_IR", "fi_FI", "fr_BE", "fr_CA", "fr_FR", "gl_ES", "he_IL", "hi_IN", "hr_HR", "hu_HU", "id_ID", "is_IS", "it_IT", "ja_JP", "kn"   , "ko_KR", "lt_LT", "lv_LV", "mn_MN", "ms_MY", "nb_NO", "nl_BE", "nl_NL", "nn_NO", "pl_PL", "pt_BR", "pt_PT", "ro_RO", "ru_RU", "sk_SK", "sl_SI", "sq_AL", "sr_RS", "sv_SE", "th_TH", "tr_TR", "uk_UA", "vi_VN", "zh_CN", "zh_HK", "zh_TW"]
    default = "en_GB"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/glpi-project/glpi/releases/download/10.0.20/glpi-10.0.20.tgz"
    sha256 = "31c3d649d4f4694b9d96a4150ff1e4ebec4844780df9f8ebb216ba1ed09bd258"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^glpi-.*\\.tgz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.3-cli",
        "php8.3-curl",
        "php8.3-fileinfo",
        "php8.3-gd",
        "php8.3-mbstring",
        "php8.3-mysqli",
        "php8.3-simplexml",
        "php8.3-xml",
        "php8.3-intl",
        "php8.3-ldap",
        "php8.3-xmlrpc",
        "php8.3-bz2",
        "php8.3-zip",
    ]

    [resources.database]
    type = "mysql"
